### ISSUE TITLE
Include statistics in the report

### ISSUE THREAD

**Issue by MahnazBehroozi** [syazdan25/SE17-Project#8]
We should summarize the statistics obtained from our survey in the form of charts, tables, figures and etc to be included in our report. This will be a form of our reasoning/motivation toward conducting our project/research.
For the sake of collecting as much as information, we will do it as late as possible by Jan. 30 9:00 PM.

**Comment by syazdan25** [comment]
I think summarizing the statistics, building charts, interpreting the result and incorporating it in report will be a tough task to do on the day of submission. Should we consider the data till Jan 29 and build the tables/figures and interpret the results so that we will have enough time. Any suggestions?

**Comment by MahnazBehroozi** [comment]
Actually, it is not a tough task and can be done in less than 3 hours. Besides that, we will do it one day before the due date. But if we see that there is no additional responses to our survey in next two days, we can do the analysis by the end of Jan. 29. Sounds good?
